// Date: 17-06-2013 22:56:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.madpc.coffee.coffeemaker;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCoffeeMaker extends ModelBase {
    //fields
    ModelRenderer Base;
    ModelRenderer Back;
    ModelRenderer Front_1;
    ModelRenderer Front_2;
    ModelRenderer Front_3;
    ModelRenderer Coffee_hole;
    
    public ModelCoffeeMaker() {
        this.textureWidth = 256;
        this.textureHeight = 32;
        
        this.Base = new ModelRenderer(this, 125, 0);
        this.Base.addBox(0F, 0F, 0F, 16, 2, 16);
        this.Base.setRotationPoint(0F, 14F, 0F);
        this.Base.setTextureSize(256, 32);
        this.Base.mirror = true;
        this.setRotation(this.Base, 0F, 0F, 0F);
        this.Back = new ModelRenderer(this, 66, 0);
        this.Back.addBox(0F, 0F, 0F, 16, 15, 8);
        this.Back.setRotationPoint(0F, 0F, 8F);
        this.Back.setTextureSize(256, 32);
        this.Back.mirror = true;
        this.setRotation(this.Back, 0F, 0F, 0F);
        this.Front_1 = new ModelRenderer(this, 16, 23);
        this.Front_1.addBox(0F, 0F, 0F, 16, 5, 2);
        this.Front_1.setRotationPoint(0F, 0F, 6F);
        this.Front_1.setTextureSize(256, 32);
        this.Front_1.mirror = true;
        this.setRotation(this.Front_1, 0F, 0F, 0F);
        this.Front_2 = new ModelRenderer(this, 24, 10);
        this.Front_2.addBox(0F, 0F, 0F, 16, 4, 1);
        this.Front_2.setRotationPoint(0F, 1F, 5F);
        this.Front_2.setTextureSize(256, 32);
        this.Front_2.mirror = true;
        this.setRotation(this.Front_2, 0F, 0F, 0F);
        this.Front_3 = new ModelRenderer(this, 0, 0);
        this.Front_3.addBox(0F, 0F, 0F, 16, 3, 2);
        this.Front_3.setRotationPoint(0F, 2F, 3F);
        this.Front_3.setTextureSize(256, 32);
        this.Front_3.mirror = true;
        this.setRotation(this.Front_3, 0F, 0F, 0F);
        this.Coffee_hole = new ModelRenderer(this, 4, 10);
        this.Coffee_hole.addBox(0F, 0F, 0F, 3, 1, 3);
        this.Coffee_hole.setRotationPoint(6F, 5F, 5F);
        this.Coffee_hole.setTextureSize(256, 32);
        this.Coffee_hole.mirror = true;
        this.setRotation(this.Coffee_hole, 0F, 0F, 0F);
    }
    
    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.Base.render(f5);
        this.Back.render(f5);
        this.Front_1.render(f5);
        this.Front_2.render(f5);
        this.Front_3.render(f5);
        this.Coffee_hole.render(f5);
    }
    
    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
    
    public void renderAll() {
        float rot = 0.0625F;
        this.Base.render(rot);
        this.Back.render(rot);
        this.Front_1.render(rot);
        this.Front_2.render(rot);
        this.Front_3.render(rot);
        this.Coffee_hole.render(rot);
    }
}
